on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rabbitmq-version:
          - 3.7.10
          - 3.7.11
          - 3.7.12
          - 3.7.13
          - 3.7.14
          - 3.7.15
          - 3.7.16
          - 3.7.17
          - 3.7.18
          - 3.7.19
          - 3.7.20
          - 3.7.21
          - 3.7.22
          - 3.7.23
          - 3.7.24
          - 3.7.25
          - 3.7.26
          - 3.7.27
          - 3.7.28
          - 3.8.0
          - 3.8.1
          - 3.8.2
          - 3.8.3
          - 3.8.4
          - 3.8.5
          - 3.8.6
          - 3.8.7
          - 3.8.8

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: docker build
      run: |
        make build
      env:
        RABBITMQ_VERSION: ${{ matrix.rabbitmq-version }}

    - name: install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt

    - name: test
      run: |
        make test
      env:
        RABBITMQ_VERSION: ${{ matrix.rabbitmq-version }}

    - name: deploy
      run: |
        docker login ghcr.io -u nameko-actions-bot -p ${{ secrets.ACTIONS_BOT_PAT }}
        docker tag nameko/nameko-rabbitmq:${{ matrix.rabbitmq-version }} ghcr.io/nameko/nameko-rabbitmq:${{ matrix.rabbitmq-version }}
        docker push ghcr.io/nameko/nameko-rabbitmq:${{ matrix.rabbitmq-version }}
      if: github.ref == 'refs/heads/master'